Advance repo
hyperledger/aries-acapy-plugins pull request #5
Opened 2023-10-17 16:40 UTC by jamshale

This PR adds another plugin `connection_update`, testing for current plugins, documentation updates and a script for common dependency and file management.

Only one additional plugin was added so far. Others are being worked on but the testing has been a bit of a learning process and I want plugins to be added that are adequately tested. Some of the plugins I want to add have a lot more logic that will be more difficult testing. 

When I was adding my first plugin to the repo I realized that we want to have isolated environments for development and testing and that quickly things were going to be difficult to manage. 

To combat this I decided to create a base empty plugin `default-empty-plugin` and a script `updater.sh` which updates the existing plugins and populates common files from it. I'm only sure the script works on linux systems currently. Some of the text commands possibly won't work on mac OS.

I tried to update the README as well as I could to make it clear how to add an existing plugin or create a new one from scratch. It is quite easy but instructions can be hard.

I'm not super happy with the naming I chose. I might change it if I can think of something better.

2023-10-17 16:48 UTC, jamshale commented on CONTRIBUTING.md
Not exactly sure what to put in this file yet. Thinking about it.

2023-10-17 16:53 UTC, jamshale commented on basicmessage_storage/pyproject.toml
> -    --ruff
This was throwing errors for me. I actually need to figure out how to do the linting still. Right now i'm just using the ruff vs code extension and not sure if all the rules are being met.

2023-10-17 16:54 UTC, jamshale commented on basicmessage_storage/setup.cfg
> -[flake8]
Didn't think this was needed anymore as we are using `ruff` ?

2023-10-17 16:56 UTC, jamshale commented on configs/multitenant-plugins.yml
Was going to add a basic single tenant config example as well. I also don't know how far we want to take example config files. Seems somewhat out of scope for this repo.

2023-10-17 19:52 UTC, esune commented on CONTRIBUTING.md
Could take inspiration from ACA-Py's [CONTRIBUTING.md](https://github.com/hyperledger/aries-cloudagent-python/blob/main/CONTRIBUTING.md)

2023-10-17 20:13 UTC, esune commented on configs/multitenant-plugins.yml
I think I agree, plugin documentation should be covered in ACA-Py already (I think).

2023-10-17 20:29 UTC, esune reviewed
This looks quite good, thank you @jamshale! I might try to run things on my machine, in the meantime tagging @dbluhm, @shaangill025 and @usingtechnology for input/review since they have more plug-in development experience than I do.

A couple of thoughts:
- unsure about having `updater.sh` require a specific OS architecture. We might want to dig deeper into making it cross-platform, but it is a good start either way.
- I am wondering if, for testing, having plug-ins added/built into the image in a more randomized way to prevent internal dependencies - unless required - and situations such as "it has to be in this sequence or it won't work" could be something we should think of?

2023-10-17 20:29 UTC, esune commented on updater.sh
> +#!/usr/bin/bash
If you haven't already: following [this](https://github.com/hyperledger/aries-cloudagent-python/blob/main/scripts/run_docker) example might help having a cross-OS compatibile script.

2023-10-18 21:33 UTC, dbluhm commented on updater.sh
How is this file intended to be used? I'm not too keen on maintaining dense bash scripts in this repo, if we can avoid it, to be honest :sweat_smile:

2023-10-18 21:33 UTC, dbluhm commented on Dockerfile
In the future, I think I'd like to see dockerfiles moved to inside of specific plugins only. I don't know that it makes sense for there to be a top level dockerfile since this repo will house plugins that someone wouldn't necessarily need/want to deploy together.

As an alternative, we could instead include a set of example dockerfiles that could aggregate plugins from this project into a single image?

I'm not against merging these changes right now though.

2023-10-18 21:42 UTC, usingtechnology commented on Dockerfile
Yeah, we could lose this file. or simply add something to documentation. When I added this, it was intended more as documentation for adding a plugin to an external image. Perhaps too confusing and plugin usage and deployment best left as pure documentation.

2023-10-18 22:29 UTC, jamshale commented on updater.sh
There will only be one. 

It allows populating new plugins with everything they need for integration testing and devcontainer development. Along with updating things for all plugins at once such as the launch.json file and whatnot.

The only reason I want to have this is I feel like this repo will be very challenging to maintain when there is many plugins and adding new plugins with all the infrastructure is a giant pain.

This is what this script is trying to solve.

2023-10-18 22:34 UTC, jamshale commented on Dockerfile
I do like it as an example of an agent with multiple plugins. But yes it doesn't need to exist.

2023-10-19 14:27 UTC, jamshale commented on updater.sh
That is a good idea. I should have thought of that. It won't take long to copy the logic.

In my opinion this is critical. I think it becomes pretty obvious when you go to add a new plugin, and think about there being dozens of plugins being contributed by different people. Even with comprehensive readme the instructions are going to be complicated and being able to manage plugins globally is going to become time consuming and error prone.

This doesn't need to be a part of this PR. I could remove it and bring it back as a python script in another PR so it's more clear what was added as a part of plugins and testing and keep it separate from the script.

2023-10-19 16:13 UTC, usingtechnology commented on Dockerfile
Let's drop the top-level Dockerfile and add an issue for documentation. We do need to let consumers know how to leverage the plugins and include them in their deployments.

2023-10-19 16:30 UTC, jamshale commented on updater.sh
@usingtechnology Sounds good. I'll do that and update the PR without it.

2023-10-19 19:38 UTC, jamshale commented
Open again. This PR will just add `connection_update` plugin and testing and address some comments.
The script will return as another task later on. Still working on testing the next plugin to be added `multitenant_provider`.

2023-10-19 20:12 UTC, usingtechnology requested changes

2023-10-19 20:25 UTC, jamshale commented on basicmessage_storage/plugin-config.yml.sample
> +auto-provision: true
Gotcha. Ya i'll remove them.

2023-10-20 17:37 UTC, usingtechnology approved these changes

2023-10-20 17:48 UTC, merged